name: Build and Deploy UserService

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: ride_sharing
          MYSQL_USER: root
          MYSQL_PASSWORD: root
        ports:
          - 3306:3306  # Expose port 3306 for MySQL to connect to
        options: --health-cmd="mysqladmin ping --silent"  # Health check to ensure MySQL is ready


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build UserService JAR
        run: mvn clean package -f ./UserService/pom.xml --no-transfer-progress

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image for UserService
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:${{ github.sha }} ./UserService

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/user-service:${{ github.sha }}
